app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//ruta para exportar a PDF información de persona
Route::get('PDFpersona/{id}','PDFController@mostrarPersona');

//rutas para exportar a PDF los listados
Route::get('PDFListadopersonaF/{dato}','PDFController@mostrarListadopersonaF');
Route::get('PDFListadopersona','PDFController@mostrarListadopersona');

Route::get('PDFListadoservicios/{dato}','PDFController@mostrarListadoserviciosF');
Route::get('PDFListadoservicios','PDFController@mostrarListadoservicios');

Route::get('PDFListadoredes/{dato}','PDFController@mostrarListadoredesF');
Route::get('PDFListadoredes','PDFController@mostrarListadoredes');

Route::get('PDFListadocelulas/{dato}','PDFController@mostrarListadocelulasF');
Route::get('PDFListadocelulas','PDFController@mostrarListadocelulas');

//Rutas para personas
Route::get('/','PersonaController@index');
Route::get('/persona/mostrar/{id}','PersonaController@mostrar');
Route::resource('/persona','PersonaController');

//Ruta para Carga Familiar
Route::get('/cargaf/crear/{id}','CargaFController@crear');
Route::post('/cargaf/registrar','CargaFController@registrar');
Route::resource('/cargaf','CargaFController');

//Ruta para Celulas
Route::resource('/celulas','CelulaController');

//Ruta para Servicio público
Route::resource('/public_service','PublicServiceController');

//Ruta para Redes
Route::resource('/redes','RedesController');

//Ruta para pastores
Route::get('/pastor/crear/{id}','PastoresController@crear');

Route::post('/pastor/registrar','PastoresController@registrar');

Route::resource('/pastor','PastoresController');

app/Models/Persona/CargaFamiliar.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;
use Maranatha\Models\Persona\Persona;
use Illuminate\Support\Facades\DB;

class CargaFamiliar extends Model
{
    protected $table = 'cargaFamiliar';
    protected $primarykey = 'id';
    protected $fillable=[
        'id','nombrep', 'apellidop','parentesco','persona_id'
    ];

    public function Persona(){
        $this->hasMany(Persona::class);
    }

    public static function mostrarCarga($id){
        return DB::table('cargaFamiliar')
            ->join('persona','persona.id','=','cargaFamiliar.persona_id')
            ->where('persona.id','=',$id)
            ->select('cargaFamiliar.*')
            ->paginate(8);
    }

    public static function eliminarCarga($persona_id){
      return DB::table('cargaFamiliar')

            ->from('cargaFamiliar')
            ->where('cargaFamiliar.persona_id','=',$persona_id)
            ->delete();

    }
}

app/Models/Persona/Celula.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;


class Celula extends Model
{
    protected $table = "celulas";
    protected $primarykey = 'id';
    protected $fillable = [
        'id','tipo','sector_id','red_id','name'
    ];

    public function red(){

        return $this->belongsTo(Redes::class);
    }

    public function pastor(){
        return $this->hasOne(Pastores::class);
    }


    public function sector(){
        return $this->hasOne(Sector::class);
    }

    public static function celula($id){
        return Celula::where('red_id','=',$id)
            ->get();
    }

    public static function union($dato){
        return DB::table('celulas')
                                ->join('sectors','sectors.id','=','celulas.sector_id')
                                ->join('red','red.id','=','celulas.red_id')
                                ->where('red.nombre','LIKE','%'.$dato.'%')
                                ->orWhere('sectors.nombreSector','LIKE','%'.$dato.'%')
                                ->orWhere('celulas.tipo','LIKE','%'.$dato.'%')
                                ->select('celulas.id','celulas.name','celulas.tipo','red.nombre as red','sectors.nombreSector as sector');
    }


}

app/Models/Persona/Direccion.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;


class Direccion extends Model
{
      protected $table = 'direccion';
      protected $primarykey = 'id';
      protected $fillable = [
        'id','municipio','estado_id','avenida','calle','sector_id','nroCasa','edificio'

      ];

    public function persona(){
        return $this->belongsTo(Persona::class);
    }




}

app/Models/Persona/EdoCivil.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;

class EdoCivil extends Model
{
    protected $table = 'edocivil';
    protected $primarykey = 'id';
    protected $fillable = [
      'id','estado'
    ];

    public function persona(){
        return $this->belongsTo(Persona::class);
    }
}

app/Models/Persona/Estado.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;

class Estado extends Model
{
    protected $table = 'estado';
    protected $primarykey = 'id';
    protected $fillable = [
      'id','nombre'
    ];
}

app/Models/Persona/Lider.php
<?php

namespace Maranatha\Models\Persona;

use Faker\Provider\fr_CA\Person;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Lider extends Model
{
    protected $table="liders";
    protected $primarykey="id";
    protected $fillable =[
        'id','celula_id','persona_id','tlf_id'
    ];

    public function celula(){
        return $this->belongsTo(Celula::class);
    }

    public function persona(){
        return $this->hasOne(Person::class);
    }


    public static function joinLiders(){
        return DB::table('liders')
            ->join('persona','persona.id','=','liders.id')
            ->select('liders.id','persona.nombre','persona.apellido')
            ->get();
    }

}

app/Models/Persona/Pastores.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Pastores extends Model
{
    protected $table = 'pastores';
    protected $primarykey = 'id';
    protected $fillable = [
      'id','nombre','apellido','tlf_id','red_id','celula_id'
    ];

    public function red(){
        return $this->hasOne(Redes::class);
    }

    public function celula(){

        return $this->hasOne(Celula::class);
    }

    public static function Busqueda($id){
        return DB::table('pastores')
        ->join('red','red.id','=','pastores.red_id')
            ->where('red.id','=',$id)
            ->select('pastores.*')
            ->get();
    }

    public static function eliminarPastor($id){
        return DB::table('pastores')

            ->from('pastores')
            ->where('pastores.red_id','=',$id)
            ->delete();

    }

}

app/Models/Persona/PublicService.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;



class PublicService extends Model
{
    protected $table = 'public_services';
    protected $primarkey= 'id';
    protected $fillable=[
        'id','tipo','encargado','sector_id','contacto'
    ];

    public static function Busqueda($dato){

        return DB::table('public_services')
            ->join('sectors','sectors.id','=','public_services.sector_id')
            ->where('sectors.nombreSector','LIKE','%'.$dato.'%')
            ->select('public_services.id','public_services.tipo','public_services.encargado','public_services.contacto','sectors.nombreSector as sector');
    }

}

app/Http/Controllers/PersonaController.php
<?php

namespace Maranatha\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\Validator;
use Maranatha\Http\Requests;
use Maranatha\Http\Requests\PersonaUpdateRequest;
use Maranatha\Models\Persona\CargaFamiliar;
use Maranatha\Models\Persona\Celula;
use Maranatha\Models\Persona\Direccion;
use Maranatha\Models\Persona\EdoCivil;
use Maranatha\Models\Persona\Estado;
use Maranatha\Models\Persona\Lider;
use Maranatha\Models\Persona\Persona;
use Maranatha\Models\Persona\Redes;

use Maranatha\Http\Controllers\Controller;
use Maranatha\Models\Persona\Telefono;
use Maranatha\Models\Persona\Sector;
use Maranatha\Http\Requests\PersonaCreateRequest;
use Session;


class PersonaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $dato = $request->dato;
        //dd($dato);
      $personas=Persona::personas($dato)->paginate(8);
      //dd($personas);

        return view('Persona.index')->with('personas',$personas)
                                            ->with('dato',$dato);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $redes = Redes::pluck('nombre','id');

        $celulas  = Celula::pluck('name','id');
        $edociviles = EdoCivil::all();
        $nombres = Estado::all();
        $sectores = Sector::all();
        //dd(Persona::mostrarDatos(1));

        return view('persona.create')->with('redes', $redes)
                                      ->with('edociviles',$edociviles)
                                      ->with('nombres',$nombres)
                                      ->with('celulas',$celulas)
                                      ->with('sectores',$sectores);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        $validador=$this->validar($request);
        //dd($validador->fails());
        if($validador->fails()){
            return redirect('persona/create')->withErrors($validador);
        }
        $direccion = new DireccionController();
        $telefono = new TelefonoController();
        $carga = new CargaFController();

        $lider_status = false;
        //dd($request['sector']['0']);
        //$celula_id=$celula->store($request);



        $direccion_id = $direccion->store($request);
        $telefono_id=$telefono->store($request);

        $status_red = true;
        $bautizo = true;

        if($request['opcion']=='si'){
            $bautizo= true;
        }
        else {$bautizo=false;}

        if($request['opcion3'] == 'siRed'){
          $status_red = true;
          $red_id = $request['red_id'];
          $celula_id = $request['celula_id'];
        }
        elseif ($request['opcion4']=='siRed2') {
          $status_red = true;
          $red_id = $request['red_id2'];
          $celula_id = null;
        }

        else {
          $status_red = false;
          $red_id = null;
          $celula_id = null;
        }

        if($request['opcion5']=='siLider'){
            $lider_status = true;
        }

        else $lider_status = false;

        if ($request['celula_id']=='') {
          $celula_id=null;
        }
        //dd($request['red_id']);
        $persona = Persona::create([
            'red_id'=> $red_id,
            'nombre' =>$request['nombre'],
            'apellido'=>$request['apellido'],
            'cedula' => $request['cedula'],
            'correo'=>$request['correo'],
            'otraIglesia'=>$request['iglesia'],
            'fecha_nac'=>$request['fecha_nac'],
            'ocupacion' =>$request['ocupacion'],
            'bautizo'=>$bautizo,
            'tiempoIglesia'=>$request['tiempo'],
            'celula_id'=>$celula_id,
            'status_red'=>$status_red,
            'direccion_id'=>$direccion_id,
            'edocivil_id'=>$request['edocivil_id'],
            'tlf_id'=>$telefono_id,
            'esLider'=>$lider_status
        ]);
        $persona->save();
        $cargaF = $carga->store($request,$persona->id);
        Session::flash('save','Se ha guardado exitosamente');

        return redirect()->route('persona.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $persona = Persona::find($id);

        return view('persona.show')->with('persona',$persona);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $redes = Redes::all();
        $edociviles = EdoCivil::all();
        $nombres = Estado::all();
        $celulas= Celula::all();
        $persona = Persona::find($id);
        $sectores = Sector::all();
        //dd(date("d-m-Y",strtotime($persona->fecha_nac)));
        $direccion = Direccion::find($persona->direccion_id);
        $cargasF = CargaFamiliar::mostrarCarga($persona->id);
        $tlf = Telefono::find($persona->tlf_id);
        $ban = 0;
        //dd($persona->tlf_id);
        return view('persona.edit',array('persona'=>$persona,'redes'=>$redes,
            'nombres'=>$nombres,'edociviles'=>$edociviles,'direccion'=>$direccion,
            'cargasF'=>$cargasF,'tlf'=>$tlf,'celulas'=>$celulas,'sectores'=>$sectores));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PersonaUpdateRequest $request, $id)
    {
        //dd($request->all());
        $personas= Persona::find($id);
        $status_red =false;
        if ($request['sectorC']!='') {
            $sector = Sector::create([
                'nombreSector'=>$request['sectorC']
            ]);
            $sector->save();
            $sector_id=$sector->id;
        }

        else {
            $sector_id = $request['sector_id'];
        }
        $direccion = Direccion::find($personas->direccion_id);

            $direccion->municipio = $request['municipio'];
            $direccion->estado_id =$request['estado_id'];
            $direccion->avenida =$request['avenida'];
            $direccion->calle =$request['calle'];
            $direccion->sector_id =$sector_id;
            $direccion->nroCasa =$request['nroCasa'];
            $direccion->edificio =$request['edificio'];

            $direccion->save();

            $telefono = Telefono::find($personas->tlf_id);

            $telefono->movil = $request['movil'];
            $telefono->casa = $request['casa'];
            $telefono->save();

            $personas->nombre = $request['nombre'];
            $personas->apellido=$request['apellido'];
            $personas->cedula= $request['cedula'];
            $personas->red_id= $request['red_id'];
            $personas->correo=$request['correo'];
            $personas->status_Red=$request['status_Red'];
            $personas->fecha_nac=$request['fecha_nac'];
            $personas->ocupacion =$request['ocupacion'];
            $personas->direccion_id=$direccion->id;
            $personas->edocivil_id=$request['edocivil_id'];
            $personas->celula_id = $request['celula_id'];
        if($request['opcion']=='si'){
            $bautizo= true;
            $personas->bautizo=$bautizo;
        }
        else {$bautizo=false;
            $personas->bautizo=$bautizo;
        }

        if($request['opcion3'] == 'siRed'){
            $status_red = true;
            $red_id = $request['red_id'];
            $celula_id = $request['celula_id'];
            $personas->status_red=$status_red;
            $personas->red_id=$red_id;
            $personas->celula_id=$celula_id;
        }
        elseif ($request['opcion4']=='siRed2') {
            $status_red = true;
            $red_id = $request['red_id2'];

            $celula_id = null;
            $personas->status_red=$status_red;
            $personas->red_id=$red_id;
            $personas->celula_id=$celula_id;
        }
            if($request['opcion5']=='siLider'){
                $lider_status = true;
                $personas->esLider=$lider_status;
            }

            else {$lider_status = false;
                $personas->esLider=$lider_status;
            }
            $personas->tlf_id=$telefono->id;

            //dd($status_red);

        $personas->save();

        Session::flash('edit','Se ha editado exitosamente');

        return redirect()->route('persona.index');

    }

    public function validar($request){
        $validador = validator($request->all(),[
            'nombre'=>'required|string|min:2',
            'apellido'=>'required|string|min:2',
            'cedula'=>'required|numeric|unique:persona,cedula',
            'fecha_nac'=>'required',
            'nombrep.*'=>'required',
            'apellidop.*'=>'required',
            'parentesco.*'=>'required',
            'correo'=>'required|email',
            'ocupacion'=>'required',
            'edocivil_id'=>'required',
            'estado_id' => 'required',
            'municipio' => 'required',
            'sector_id' => 'required',
            'calle' => 'required',
            'tiempo' => 'required',
            'movil'=>'required|digits:11',
            'casa'=>'digits:11',
        ]);
        return $validador;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $persona = Persona::find($id);
        $cargasF = CargaFamiliar::eliminarCarga($persona->id);

resources/views/Persona/partials_edit/basics.blade.php
<h3> Llene sus datos</h3>
<div class="col-xs-6 ">
    <div class="form-group">
        {!!Form::label('Nombre')!!}
        {!!Form::text('nombre',$persona->nombre,['id'=>'nombre','class'=>'form-control','placeholder'=>'Ingrese el nombre'])!!}
    </div>
</div>
<div class="col-xs-6">
    <div class="form-group">
        {!! Form::label('Apellido') !!}
        {!! Form::text('apellido',$persona->apellido,['id'=>'apellido','class'=>'form-control','placeholder'=>'Ingrese el apellido']) !!}
    </div>
</div>
<div class="col-xs-6">
    <div class="form-group">

        {!! Form::label('Cédula') !!}
        {!! Form::text('cedula',$persona->cedula,['id'=>'cedula','class'=>'form-control','placeholder'=>'Ingrese la cédula']) !!}

    </div>
</div>
<div class="col-xs-6">
    <div class="form-group">

        {!! Form::label('Fecha de nacimiento') !!}
        <input type="date" name="fecha_nac" class="form-control" value="{{$persona['fecha_nac']}}" >
    </div>
</div>

<div class="col-xs-6">
    <div class="form-group">
        {!! Form::label('Ocupación') !!}
        {!! Form::text('ocupacion',$persona->ocupacion,['id'=>'ocupacion','class'=>'form-control','placeholder'=>'Ingrese su ocupacion']) !!}
    </div>
</div>

<div class="col-xs-6">
    <div class="form-group">
        {!! Form::label('Estado Civil') !!}
        <select id = 'edocivil_id' name = 'edocivil_id' class = 'form-control' placeholder = "Seleccione su estado civil">
            @foreach($edociviles as $edocivil)
                @if($persona->edocivil_id==$edocivil->id)
                <option selected = "selected"  value={{$edocivil['id']}}>{{$edocivil['estado']}}</option>
                @else <option value={{$edocivil['id']}}>{{$edocivil['estado']}}</option>
            @endif
            @endforeach
        </select>

    </div>
</div>
<div class="col-xs-6">
    <div class="form-group">

        {!! Form::label('Correo') !!}
        {!! Form::email('correo',$persona->correo,['id'=>'correo','class'=>'form-control','placeholder'=>'Ingrese el correo']) !!}

    </div>
</div>

resources/views/Persona/partials_edit/cargaf.blade.php
<h3> Carga Familiar</h3>
 @include('alerts.errorajax')
 @include('alerts.successajax')
<div class="container">
  <div class="col-xs-10 col-md-10">
      <div id="msj-success" class="alert alert-success alert-dismissible" role="alert" style="display:none">
          <strong> Familiar Agregado Correctamente.</strong>
      </div>
      <div id = "listaCarga" class="panel panel-info">

          <div class="panel-heading">
              <strong>Carga Familiar</strong>
              <div class="navbar navbar-right" style=" margin-top: 1px;">
                  <a type="button" href="{{URL::to('cargaf/crear',$persona->id)}}" class="btn btn-success btn-sm" style="margin-bottom: 1px; margin-top: -5px;margin-right: 8px;padding: 3px 20px;" >Agregar</a>
              </div>

          </div>

          <div class="panel-body">
              <table class="table table-responsive">
                  <thead>
                  <th class="col-md-3">Nombre</th>
                  <th class="col-md-3">Apellido</th>
                  <th class="col-md-3">Parentesco</th>
                  <th class ="col-md-3">Accion</th>
                  </thead>

                  <tbody>

                  @foreach($cargasF as $cargaf)
                      <tr>
                          <td>{{$cargaf->nombrep}}</td>
                          <td>{{$cargaf->apellidop}}</td>
                          <td>{{$cargaf->parentesco}}</td>
                          <td> <a type="button" href="{{route('cargaf.edit',$cargaf->id)}}" title="Editar" class='btn btn-social-icon btn-info'>
                                  <i class="fa fa-edit"></i>
                              </a>

                              <a type="button" href="{{route('cargaf.show',$cargaf->id)}}" title="Eliminar" class='btn btn-social-icon btn-danger'>
                                  <i class="fa fa-trash"></i>
                              </a>

                          </td>
                      </tr>
                  @endforeach
                  </tbody>

              </table>

          </div>


      </div>

      </div>

</div>

resources/views/Persona/partials_edit/direccion.blade.php
<h3>Direccion donde reside</h3>

<div class="form-group col-xs-6">
    {!! Form::label('Estado') !!}
    <select id="estado_id" name="estado_id" class = "form-control" placeholder="Seleccione el estado..." >
        @foreach($nombres as $nombre)
          @if ($nombre->id==$direccion->estado_id)
            <option selected= "selected" value={{$nombre['id']}}>{{$nombre['nombre']}}</option>
          @else
            <option value={{$nombre['id']}}>{{$nombre['nombre']}}</option>
          @endif

        @endforeach
    </select>
</div>

<div class="form-group col-md-6">
    <label>Municipio</label>
    <input type="text" id="municipio" name="municipio" class="form-control" placeholder="Ingrese el municipio" value="{{$direccion['municipio']}}">
</div>

<div class="form-group col-xs-6">
    {!!Form::label('Avenida ')!!}
    <input type="text" name="avenida" id="avenida" class="form-control" value="{{$direccion['avenida']}}" placeholder="Ingrese la avenida">
</div>



<div class="form-group col-xs-6" >

    {!! Form::label('Sector') !!}
    <div class="row">
        <div id="divSectores" class="col-xs-5">
            <select name="sector_id" id="sector_id" class="form-control">
                <option value="-1"></option>
                <option value="0">Agregar Sector</option>
                @foreach($sectores as $sector)
                    @if($sector->id==$direccion->sector_id)
                    <option selected="selected" value="{{$sector->id}}">{{$sector->nombreSector}}</option>
                    @else
                        <option value="{{$sector->id}}">{{$sector->nombreSector}}</option>
                    @endif
                @endforeach
            </select>
        </div>

        <div id="sectorCelula" class="col-xs-4" style="display:none;">
            <input id="sectorC" name="sectorC" type="text"  class="form-control" placeholder="Ingrese el sector a agregar">
        </div>
        <div id="AgregarSectores" class="col-xs-1" style="display: none;">
            <button id="agregarSector" type="button" onclick="addSector()" class="btn btn-default btn-sm" title="Agregar Sector">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </div>

    </div>
</div>

<div class="form-group col-xs-6">
    {!!Form::label('Calle')!!}
    <input type="text" name="calle" id="calle" class="form-control" value="{{$direccion['calle']}}" placeholder="Ingrese la calle">
</div>

<div class="form-group col-xs-6">
    {!!Form::label('Nro de casa')!!}
    <input type="text" name="nroCasa" id="nroCasa" class="form-control" value="{{$direccion['nroCasa']}}" placeholder="Ingrese la avenida">

</div>
<div class = "form-group col-xs-6">
    {!! Form::label('Edificio') !!}
    <input type="text" name="edificio" id="edificio" class="form-control" value="{{$direccion['edificio']}}" placeholder="Ingrese el numero del edificio">
</div>

resources/views/Persona/partials_edit/iglesia.blade.php
<h3>Datos eclesiásticos</h3>
<div class="form-group col-xs-2">
    {!! Form::label('Bautizado?') !!}
    <div>
        @if($persona->bautizo==1)
            <input type="radio" class="si" name="opcion" value="si" checked> Sí
            <input type="radio" class="no" name="opcion" value="no"> No
        @else
            <input type="radio" class="si" name="opcion" value="si" > Sí
            <input type="radio" class="no" name="opcion" value="no"checked> No
            @endif
    </div>
</div>

<div class="form-group col-xs-2">
    {!! Form::label('De otra Iglesia') !!}
    <div >
        @if($persona->otraIglesia==1)
        <input type="radio" class="si" name="opcion2" value="siI" checked> Sí
        <input type="radio" class="no" name="opcion2" value="noI"> No
            @else
            <input type="radio" class="si" name="opcion2" value="siI" > Sí
            <input type="radio" class="no" name="opcion2" value="noI" checked> No
            @endif
    </div>
</div>
<div id="Otra" class="form-group col-xs-3"  style="display: none;">
    {!! Form::label('Ministerio') !!}
    {!! Form::text('iglesia',$persona->otraIglesia,['id'=>'iglesia','placeholder'=>'Ingrese el nombre del ministerio','class'=>'form-control'] ) !!}
</div>

<div class="form-group col-xs-3">
    {!! Form::label('Tiempo en la iglesia') !!}
    {!! Form::date('tiempo',$persona->tiempoIglesia,['id'=>'tiempo','class'=>'form-control','placeholder'=>'Ingrese el tiempo en la iglesia']) !!}
</div>

<div class="form-group col-xs-2 ">
    {!! Form::label('Pertenece a alguna red?') !!}
    <div >
        @if($persona->status_red==1)
        <input type="radio" id="valorRed" class="siRed" name="opcion3" value="siRed" checked> Sí
        <input type="radio" id="valorRed" class="noRed" name="opcion3" value="noRed"> No
            @else
            <input type="radio" id="valorRed" class="siRed" name="opcion3" value="siRed"> Sí
            <input type="radio" id="valorRed" class="noRed" name="opcion3" value="noRed" checked> No
            @endif
    </div>
</div>
<div  id="divYes" class="form-group col-xs-3" style="display:none;">

    {!!Form::label('Red a la que pertenece:')!!}
    <select class="form-control" placeholder="Selecciona una red" id="red_id" name = "red_id">
        @foreach($redes as $red)
            @if($red->id ==$persona->red_id)
                <option selected="selected" value="{{$red['id']}}">{{$red['nombre']}}</option>
            @else <option  value="{{$red['id']}}">{{$red['nombre']}}</option>
            @endif
            @endforeach
    </select>
</div>

<div id="esLider" class="form-group col-xs-4" style="display: none">
    <label>Es líder de célula?</label>
    <div >
        @if($persona->esLider==1)
        <input type="radio" class="siLider" name="opcion5" value="siLider" checked> Sí
        <input type="radio" class="noLider" name="opcion5" value="noLider"> No
            @else <input type="radio" class="siLider" name="opcion5" value="siLider" > Sí
        <input type="radio" class="noLider" name="opcion5" value="noLider" checked> No
            @endif
    </div>
</div>

<div id="cell" name="cell" class="form-group col-xs-4" style="display: none;">
    {!! Form::label('Célula a la que pertenece') !!}
    <select class="form-control" name="celula_id" id="celula_id">
      @foreach ($celulas as $celula)
        @if ($celula->id==$persona->celula_id)
          <option selected="selected" value="{{$celula->id}}">{{$celula->name}}</option>
        @else
          <option value="{{$celula->id}}">{{$celula->name}}</option>
        @endif
      @endforeach
    </select>

</div>

<div id="divNo" class="form-group col-xs-4" style="display: none;">
    {!! Form::label('Desea pertenecer a una?') !!}
    <div >
        <input type="radio" class="siRed2" name="opcion4" value="siRed2"> Sí
        <input type="radio" class="no" name="opcion4" value="noRed"> No
    </div>
</div>

<div id="divYes2" class="form-group col-xs-3" style="display:none;">

    {!!Form::label('Red')!!}
    {!! Form::select('red_id2',$redes,null,['placeholder'=>'Selecciona una red','class'=>'form-control','id'=>'red_id2']) !!}

</div>