app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//ruta para exportar a PDF información de persona
Route::get('PDFpersona/{id}','PDFController@mostrarPersona');

//rutas para exportar a PDF los listados
Route::get('PDFListadopersonaF/{dato}','PDFController@mostrarListadopersonaF');
Route::get('PDFListadopersona','PDFController@mostrarListadopersona');

Route::get('PDFListadoservicios/{dato}','PDFController@mostrarListadoserviciosF');
Route::get('PDFListadoservicios','PDFController@mostrarListadoservicios');

Route::get('PDFListadoredes/{dato}','PDFController@mostrarListadoredesF');
Route::get('PDFListadoredes','PDFController@mostrarListadoredes');

Route::get('PDFListadocelulas/{dato}','PDFController@mostrarListadocelulasF');
Route::get('PDFListadocelulas','PDFController@mostrarListadocelulas');

//Rutas para personas
Route::get('/','PersonaController@index');
Route::get('/persona/mostrar/{id}','PersonaController@mostrar');
Route::resource('/persona','PersonaController');

//Ruta para Carga Familiar
Route::get('/cargaf/crear/{id}','CargaFController@crear');
Route::post('/cargaf/registrar','CargaFController@registrar');
Route::resource('/cargaf','CargaFController');

//Ruta para Celulas
Route::resource('/celulas','CelulaController');

//Ruta para Servicio público
Route::resource('/public_service','PublicServiceController');

//Ruta para Redes
Route::resource('/redes','RedesController');

//Ruta para pastores
Route::get('/pastor/crear/{id}','PastoresController@crear');

Route::post('/pastor/registrar','PastoresController@registrar');

Route::resource('/pastor','PastoresController');

app/Models/Persona/Celula.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;


class Celula extends Model
{
    protected $table = "celulas";
    protected $primarykey = 'id';
    protected $fillable = [
        'id','tipo','sector_id','red_id','name'
    ];

    public function red(){

        return $this->belongsTo(Redes::class);
    }

    public function pastor(){
        return $this->hasOne(Pastores::class);
    }


    public function sector(){
        return $this->hasOne(Sector::class);
    }

    public static function celula($id){
        return Celula::where('red_id','=',$id)
            ->get();
    }

    public static function union($dato){
        return DB::table('celulas')
                                ->join('sectors','sectors.id','=','celulas.sector_id')
                                ->join('red','red.id','=','celulas.red_id')
                                ->where('red.nombre','LIKE','%'.$dato.'%')
                                ->orWhere('sectors.nombreSector','LIKE','%'.$dato.'%')
                                ->orWhere('celulas.tipo','LIKE','%'.$dato.'%')
                                ->select('celulas.id','celulas.name','celulas.tipo','red.nombre as red','sectors.nombreSector as sector');
    }


}

app/Http/Controllers/CelulaController.php
<?php

namespace Maranatha\Http\Controllers;

use Illuminate\Http\Request;

use Maranatha\Http\Requests;
use Maranatha\Http\Requests\CelulaCreateRequest;
use Maranatha\Models\Persona\Celula;
use Maranatha\Models\Persona\Persona;
use Maranatha\Models\Persona\Redes;
use Maranatha\Models\Persona\Sector;
use Session;

class CelulaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $dato = $request->red;
        $celulas = Celula::union($request->red)->paginate(8);
        $lideres = Persona::lideresNo();
        //dd($lideres);
        return view('Celula.index')->with('celulas',$celulas)
                                    ->with('lideres',$lideres)
                                    ->with('dato',$dato);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $redes = Redes::pluck('nombre','id');
        $sectores = Sector::all();
        //dd($redes);
        return view('Celula.create')->with('redes',$redes)
                                    ->with('sectores',$sectores);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CelulaCreateRequest $request)
    {
        //dd($request['sector_id']);
        if ($request['sectorC']!='') {
          $sector = Sector::create([
              'nombreSector'=>$request['sectorC']
          ]);
          $sector->save();
          //dd($sector->id);
          $sector_id=$sector->id;
        }

        else {
          $sector_id = $request['sector_id'];
        }
        $cell = Celula::all()->last();
        if($cell ==null) $cont=1;
        else{$cont=$cell->id+1;}
        //dd($cont);
        $celula = Celula::create([
            'name'=>'Maranatha-CS'.$cont,
            'sector_id'=>$sector_id,
            'tipo'=>$request['tipoC'],
            'red_id'=>$request['red_idCelula']
        ]);


        $celula->save();

        Session::flash('save','La celula '.$celula->name.' se la registrado satisfactoriamente');
        return redirect()->route('celulas.index');
    }

    public function registrar(CelulaCreateRequest $request,$id){
        $lider = Persona::find($id);
        //dd($request['red_id']);
        dd($request['red_idCelula']);
        $sector = Sector::create([
            'nombreSector'=>$request['sector_id']
        ]);
        $sector->save();

        $cont = Celula::all()->last();
        $celula = Celula::create([
            'name'=>'Maranatha-CS'.($cont+1),
            'sector_id'=>$sector->id,
            'tipo'=>$request['tipoC'],
            'red_id'=>$request['red_idCelula']
        ]);

        $celula->save();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $cell = Celula::find($id);
      $sectores = Sector::all();
      $redes = Redes::all();
      return view('Celula.show',compact('cell','sectores','redes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cell = Celula::find($id);
        $sectores = Sector::all();
        $redes = Redes::all();
        return view('Celula.edit',compact('cell','sectores','redes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cell = Celula::find($id);
        $cell->tipo = $request['tipoC'];
        $cell->red_id =$request['red_idCelula'];
        $cell->sector_id = $request['sector_id'];
        $cell->save();

        Session::flash('edit','La celula '.$cell->name.' se ha editado satisfactoriamente');
        return redirect()->route('celulas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cell = Celula::find($id);

        //dd($cell);
        $cell->delete();
        Session::flash('delete','Se ha eliminado satisfactoriamente');
        return redirect()->route('celulas.index');
    }
}

resources/views/Celula/create.blade.php
@extends('layouts.master')

@section('title')

@section('content')
    {!!Html::style('css/example.css')!!}

    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-1">
            @include('partials.messages')
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <span>Agregar Celula</span>
                    </div>

                    <div class="panel-body">

    {!! Form::open(['id'=>'idForm','route' =>'celulas.store','method'=>'POST']) !!}


    <div id="celulaSector" class="form-group col-xs-12" >

        {!! Form::label('Sector') !!}
        <div class="row">
            <div id="divSectores" class="col-xs-4">
                <select name="sector_id" id="sector_id" class="form-control">
                    <option value="-1"></option>
                    <option value="0">------Agregar Sector------</option>
                    @foreach($sectores as $sector)
                        <option value="{{$sector->id}}">{{$sector->nombreSector}}</option>
                        @endforeach
                </select>
            </div>

            <div id="sectorCelula" class="col-xs-4" style="display:none;">
                <input id="sectorC" name="sectorC" type="text"  class="form-control" placeholder="Ingrese el sector a agregar">
            </div>
            <div id="AgregarSectores" class="col-xs-4" style="display: none;">
                <button id="agregarSector" type="button" onclick="addSector()" class="btn btn-default btn-sm" title="Agregar Sector">
                    <span class="glyphicon glyphicon-plus"></span>
                </button>
            </div>

        </div>
    </div>

    <div id="tipoCelula" class="form-group col-xs-6">
        <label>Tipo:</label>
        <select  name="tipoC" class="form-control">
            <option value="0"></option>
            <option value="Evangelista">Evangelista</option>
            <option value="Discipulado">Discipulado</option>
        </select>
    </div>

    <div  id="divYes" class="form-group col-xs-6">

        {!!Form::label('Red a la que pertenece:')!!}

        {!! Form::select('red_idCelula',$redes,null,['placeholder'=>'Selecciona una red','class'=>'form-control','id'=>'red_idCelula']) !!}

        </div>

        <div class="col-md-6 col-md-offset-1">

            <button class="btn btn-success btn-md pull-right" type="submit">Registrar</button>

        </div>
    </div>

            {!! Form::close() !!}

            </div>
        </div>
    </div>
</div>
    </div>

@endsection
@section('scripts')
    {!! Html::script('js/showDivs.js') !!}
@endsection

resources/views/Celula/edit.blade.php
@extends('layouts.master')

@section('title')

@section('content')
  {!!Html::style('css/example.css')!!}

<div class="container">
  <div class="row">
      <div class="col-md-8 col-md-offset-1">
        @include('partials.messages')
          <div class="panel panel-primary">
              <div class="panel-heading">
                  <span>Agregar Celula</span>
              </div>

              <div class="panel-body">

{!! Form::open(['id'=>'idForm','route' =>['celulas.update',$cell->id],'method'=>'PUT']) !!}

<div class="col-xs-4">
  <label for="">Célula</label>
  <input type="text" class="form-control" name="cell" value="{{$cell->name}}" readonly="readonly">
</div>
<div id="celulaSector" class="form-group col-xs-12" >

  {!! Form::label('Sector') !!}
  <div class="row">
      <div id="divSectores" class="col-xs-4">
          <select name="sector_id" id="sector_id" class="form-control">
              <option value="-1"></option>
              <option value="0">------Agregar Sector------</option>
              @foreach($sectores as $sector)
                @if ($sector->id==$cell->sector_id)
                  <option selected="selected"value="{{$sector->id}}">{{$sector->nombreSector}}</option>
                @else
                  <option value="{{$sector->id}}">{{$sector->nombreSector}}</option>
                @endif

                  @endforeach
          </select>
      </div>

      <div id="sectorCelula" class="col-xs-4" style="display:none;">
          <input id="sectorC" name="sectorC" type="text"  class="form-control" placeholder="Ingrese el sector a agregar">
      </div>
      <div id="AgregarSectores" class="col-xs-4" style="display: none;">
          <button id="agregarSector" type="button" onclick="addSector()" class="btn btn-default btn-sm" title="Agregar Sector">
              <span class="glyphicon glyphicon-plus"></span>
          </button>
      </div>

  </div>
</div>

<div id="tipoCelula" class="form-group col-xs-6">
  <label>Tipo:</label>
  <select  name="tipoC" class="form-control">
      <option value="0"></option>
      @if ($cell->tipo=='Evangelista')
        <option selected="selected" value="Evangelista">Evangelista</option>
        <option value="Discipulado">Discipulado</option>
      @else
        <option value="Evangelista">Evangelista</option>
        <option value="Discipulado">Discipulado</option>
      @endif

  </select>
</div>

<div  id="divYes" class="form-group col-xs-6">

  {!!Form::label('Red a la que pertenece:')!!}
  <select class="form-control" name="red_idCelula" id="red_idCelula">
    @foreach($redes as $red)
        @if($red->id ==$cell->red_id)
            <option selected="selected" value="{{$red['id']}}">{{$red['nombre']}}</option>
        @else <option  value="{{$red['id']}}">{{$red['nombre']}}</option>
        @endif
        @endforeach
  </select>

  </div>

  <div class="col-md-6 col-md-offset-1">

      <button class="btn btn-success btn-md pull-right" type="submit">Editar</button>

  </div>
</div>

      {!! Form::close() !!}

      </div>
  </div>
</div>
</div>
</div>

@endsection
@section('scripts')
{!! Html::script('js/showDivs.js') !!}
@endsection

resources/views/Celula/index.blade.php
@extends('layouts.master')

@section('title','Listado de células')

@section('content')
    {!!Html::style('css/example.css')!!}


@include('partials.messages')

{!!Html::style('css/example.css')!!}
        <!-- Main component for a primary marketing message or call to action -->
<div class="container">
    <div class="row">
        <div class="col-md-10">

            {!! Form::open(['route'=>'celulas.index','method'=>'GET']) !!}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="col-xs-8">
                        <button class="btn btn-info btn-flat" type="submit" title="Todos las celulas"  >
                            <span class="glyphicon glyphicon-home"></span> Lista Completa
                        </button>
                        @if($dato==null)
                            <a href="{{URL::to('PDFListadocelulas')}}" class="btn btn-success" type="button">Exportar PDF</a>
                        @else
                            <a href="{{URL::to('PDFListadocelulas',$dato)}}" class="btn btn-success" type="button">Exportar PDF</a>
                        @endif
                    </div>

                    <div class="input-group input-group-sm col-xs-offset-4">
                        <input type="text" name="red" class="form-control" placeholder="Ingrese sector,red o tipo" id="dato_buscado">
                            <span class="input-group-btn">
                              <button class="btn btn-info btn-flat" type="submit" title="Buscar celula">
                                  <span class="glyphicon glyphicon-search"></span>
                              </button>
                            </span>
                    </div>
                    {!! Form::close() !!}

                </div>

                <div class="panel-body">

                    <table class="table table-bordered">
                        <thead>
                        <th class="col-md-2">Nombre de celula</th>
                        <th class="col-md-2">Tipo</th>
                        <th class="col-md-2">Red</th>
                        <th class="col-md-2">Sector</th>
                        <th class="col-md-2">Lideres</th>
                        <th class="col-md-2">Accion</th>


                        </thead>
                        <tbody>


                        @foreach($celulas  as $celula)
                            <tr>
                                <td>
                                    {{$celula->name}}
                                </td>

                                <td>
                                    {{$celula->tipo}}
                                </td>

                                <td>
                                    {{$celula->red}}
                                </td>

                                <td>
                                    {{$celula->sector}}
                                </td>

                                <td>
                                    @foreach ($lideres as $lider)
                                        @if ($lider->celula_id==$celula->id)
                                            {{$lider->nombre}} {{$lider->apellido}}<br>
                                        @endif
                                    @endforeach

                                </td>

                                <td> <a type="button" href="{{route('celulas.edit',$celula->id)}}" title="Editar" class='btn btn-social-icon btn-info'>
                                        <i class="fa fa-edit"></i>
                                    </a>

                                    <a type="button" href="{{route('celulas.show',$celula->id)}}" title="Eliminar" class='btn btn-social-icon btn-danger'>
                                        <i class="fa fa-trash"></i>
                                    </a>

                                </td>
                            </tr>

                        @endforeach
                        </tbody>


                    </table>

                    <div class="text-center">
                        {!! $celulas->links() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@endsection
@section('scripts')
    {!! Html::script('js/showDivs.js') !!}
@endsection

resources/views/Celula/listadocelulas.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Listado de Células</title>
    <style>
        table, td, th {
            border: 1px solid #ddd;
            text-align: center;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            padding: 15px;
        }
        h3{
            text-align: center;
        }
        #page-wrap { padding: 80px; }
    </style>

</head>

<body>
<div id="page-wrap">
    <img src="./img/logo.png" style="margin-top:-50px;" align="center">
    <h3>Listado de Células</h3>
    <table >

        <tbody>
        <tr>
            <th >Nombre de celula</th>
            <th >Tipo</th>
            <th >Red</th>
            <th >Sector</th>
            <th >Lideres</th>
        </tr>

        @foreach($celulas  as $celula)
            <tr>
                <td>
                    {{$celula->name}}
                </td>

                <td>
                    {{$celula->tipo}}
                </td>

                <td>
                    {{$celula->red}}
                </td>

                <td>
                    {{$celula->sector}}
                </td>

                <td>
                    @foreach ($lideres as $lider)
                        @if ($lider->celula_id==$celula->id)
                            {{$lider->nombre}} {{$lider->apellido}}<br>
                        @endif
                    @endforeach

                </td>

            </tr>

        @endforeach
        </tbody>


    </table>


</div>
</body>
</html>

resources/views/Celula/show.blade.php
@extends('layouts.master')

@section('title')

@section('content')
  {!!Html::style('css/example.css')!!}
   <!-- Main component for a primary marketing message or call to action -->
<div class="container">
  <div class="row">
    <div class="col-md-10">

  {!! Form::open(['id'=>'idForm','route' =>['celulas.destroy',$cell->id],'method'=>'DELETE']) !!}
    <div class="form-group">
      <label for="exampleInputPassword1">Desea eliminar esta célula:</label>
    </div>
    <div class="form-group">
      <label>Célula</label>
      {{$cell->name}}
    </div>

    {!!Form::submit('Eliminar',['name'=>'delete','id'=>'delete','content'=>'<span>Eliminar</span>',
    'class'=>'btn btn-danger btn-sm m-t-10'])!!}

    <a type="button" name="cancelar" href="{{route('celulas.index')}}" class="btn btn-default btn-sm m-t-10">Cancelar</a>

        {!! Form::close() !!}
</div>
</div>
    </div>

@endsection