app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//ruta para exportar a PDF información de persona
Route::get('PDFpersona/{id}','PDFController@mostrarPersona');

//rutas para exportar a PDF los listados
Route::get('PDFListadopersonaF/{dato}','PDFController@mostrarListadopersonaF');
Route::get('PDFListadopersona','PDFController@mostrarListadopersona');

Route::get('PDFListadoservicios/{dato}','PDFController@mostrarListadoserviciosF');
Route::get('PDFListadoservicios','PDFController@mostrarListadoservicios');

Route::get('PDFListadoredes/{dato}','PDFController@mostrarListadoredesF');
Route::get('PDFListadoredes','PDFController@mostrarListadoredes');

Route::get('PDFListadocelulas/{dato}','PDFController@mostrarListadocelulasF');
Route::get('PDFListadocelulas','PDFController@mostrarListadocelulas');

//Rutas para personas
Route::get('/','PersonaController@index');
Route::get('/persona/mostrar/{id}','PersonaController@mostrar');
Route::resource('/persona','PersonaController');

//Ruta para Carga Familiar
Route::get('/cargaf/crear/{id}','CargaFController@crear');
Route::post('/cargaf/registrar','CargaFController@registrar');
Route::resource('/cargaf','CargaFController');

//Ruta para Celulas
Route::resource('/celulas','CelulaController');

//Ruta para Servicio público
Route::resource('/public_service','PublicServiceController');

//Ruta para Redes
Route::resource('/redes','RedesController');

//Ruta para pastores
Route::get('/pastor/crear/{id}','PastoresController@crear');

Route::post('/pastor/registrar','PastoresController@registrar');

Route::resource('/pastor','PastoresController');

app/Models/Persona/CargaFamiliar.php
<?php

namespace Maranatha\Models\Persona;

use Illuminate\Database\Eloquent\Model;
use Maranatha\Models\Persona\Persona;
use Illuminate\Support\Facades\DB;

class CargaFamiliar extends Model
{
    protected $table = 'cargaFamiliar';
    protected $primarykey = 'id';
    protected $fillable=[
        'id','nombrep', 'apellidop','parentesco','persona_id'
    ];

    public function Persona(){
        $this->hasMany(Persona::class);
    }

    public static function mostrarCarga($id){
        return DB::table('cargaFamiliar')
            ->join('persona','persona.id','=','cargaFamiliar.persona_id')
            ->where('persona.id','=',$id)
            ->select('cargaFamiliar.*')
            ->paginate(8);
    }

    public static function eliminarCarga($persona_id){
      return DB::table('cargaFamiliar')

            ->from('cargaFamiliar')
            ->where('cargaFamiliar.persona_id','=',$persona_id)
            ->delete();

    }
}

resources/views/CargaFamiliar/create.blade.php
@extends('layouts.master')
@section('title')
@section('content')
@include('partials.messages')

{!!Html::style('css/example.css')!!}
        <!-- Main component for a primary marketing message or call to action -->
<div class="container">
    <div class="row">
        <div class="col-md-10">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span>Agregar Familiar</span>
                </div>

                <div class="panel-body">

                    {!! Form::open(['id'=>'idModalCarga','url'=>'cargaf/registrar','method'=>'POST']) !!}


                    <div class="form-group col-xs-4">
                        {!! Form::label('Nombre') !!}
                        {!! Form::text('nombrep',null,['id'=>'nombrep','class'=>'form-control','placeholder'=>'Ingrese el nombre del pastor']) !!}

                    </div>

                    <div class="form-group col-xs-4">
                        {!! Form::label('Apellido') !!}
                        {!! Form::text('apellidop',null,['id'=>'apellidop','class'=>'form-control','placeholder'=>'Ingrese el apellido del pastor']) !!}

                    </div>
                    <div class="form-group col-xs-4">
                        {!! Form::label('Parentesco') !!}
                        {!!Form::select('parentesco',["Padre"=>'Padre',"Madre"=>'Madre',"Esposo(a)"=>'Esposo(a)',"Hijo(a)"=>'Hijo(a)',
                        "Hermano(a)"=>'Hermano(a)',"Otro"=>'Otro'],null,['id'=>'parentesco','class' =>'form-control'])!!}
                    </div>

                    <input type="hidden" name="persona_id" value="{{$id}}" id="persona_id">


                </div>
                <div class="modal-footer">

                    <button class="btn btn-success btn-md" type="submit">Registrar</button>
                    <a type="button" href="{{route('persona.edit',$id)}}" class="btn btn-default" onclick="stepCarga()">Cancelar</a>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
    {!! Html::script('js/stepCarga.js') !!}
@endsection

resources/views/CargaFamiliar/edit.blade.php
@extends('layouts.master')
@section('title')
@section('content')
@include('partials.messages')

{!!Html::style('css/example.css')!!}
        <!-- Main component for a primary marketing message or call to action -->
<div class="container">
    <div class="row">
        <div class="col-md-10">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span>Editar Familiar</span>
                </div>

                <div class="panel-body">

                    {!! Form::model($carga,['id'=>'idFormEdit','route' =>['cargaf.update',$carga->id],'method'=>'PUT']) !!}

                    <div class="form-group col-xs-4">
                        {!! Form::label('Nombre') !!}
                        {!! Form::text('nombrep',null,['id'=>'nombrep','class'=>'form-control','placeholder'=>'Ingrese el nombre del pastor']) !!}

                    </div>

                    <div class="form-group col-xs-4">
                        {!! Form::label('Apellido') !!}
                        {!! Form::text('apellidop',null,['id'=>'apellidop','class'=>'form-control','placeholder'=>'Ingrese el apellido del pastor']) !!}

                    </div>
                    <div class="form-group col-xs-4">
                        {!! Form::label('Parentesco') !!}
                        {!!Form::select('parentesco',["Padre"=>'Padre',"Madre"=>'Madre',"Esposo(a)"=>'Esposo(a)',"Hijo(a)"=>'Hijo(a)',
                        "Hermano(a)"=>'Hermano(a)',"Otro"=>'Otro'],null,['id'=>'parentesco','class' =>'form-control'])!!}
                    </div>




                </div>
                <div class="modal-footer">

                    <button class="btn btn-success btn-md" type="submit">Editar</button>
                    <a type="button" href="{{route('persona.edit',$carga->persona_id)}}" class="btn btn-default" onclick="stepCarga()">Cancelar</a>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@endsection
@section('scripts')
    {!!Html::script('js/step.js')!!}
    {!!Html::script('js/addField.js')!!}
@endsection

resources/views/CargaFamiliar/show.blade.php
@extends('layouts.master')

@section('title')

@section('content')
{!!Html::style('css/example.css')!!}
        <!-- Main component for a primary marketing message or call to action -->
<div class="container">
    <div class="row">
        <div class="col-md-10">

            {!! Form::open(['id'=>'idForm','route' =>['cargaf.destroy',$carga->id],'method'=>'DELETE']) !!}
            <div class="form-group">
                <label for="exampleInputPassword1">Desea borrar a este familiar:</label>
            </div>
            <div class="form-group">
                <label>Familiar: </label>
                {{$carga->nombrep}} {{$carga->apellidop}}
            </div>

            {!!Form::submit('Eliminar',['name'=>'delete','id'=>'delete','content'=>'<span>Eliminar</span>',
            'class'=>'btn btn-danger btn-sm m-t-10'])!!}

            <a type="button" name="cancelar" href="{{route('redes.edit',$carga->persona_id)}}" class="btn btn-default btn-sm m-t-10">Cancelar</a>

            {!! Form::close() !!}
        </div>
    </div>
</div>

@endsection